% MATLAB_BEGINNER_CLOUD_SETUP.m
% Copy and paste this ENTIRE script into MATLAB
% No MATLAB experience needed - just follow the prompts!
% Generated: June 16, 2025

%% ========================================================================
%% STEP 1: BASIC SETUP (Run this once after your EC2 instance is ready)
%% ========================================================================

fprintf('🚀 MATLAB Cloud Worker Setup for Beginners\n');
fprintf('===========================================\n\n');

% REPLACE THIS with your actual EC2 IP address from AWS console
EC2_IP = 'YOUR-EC2-INSTANCE-IP-HERE';  % Example: '3.45.67.89'

% REPLACE THIS with the path to your SSH key
KEY_FILE = 'C:\Users\mahia\New_Flashloan\matlab-worker-key.pem';

% Check if you've updated the IP address
if strcmp(EC2_IP, 'YOUR-EC2-INSTANCE-IP-HERE')
    fprintf('❌ STOP! You need to update the EC2_IP above with your actual IP\n');
    fprintf('💡 Get your IP from AWS console after running aws_setup_commands.sh\n');
    fprintf('💡 Then come back and run this script again\n');
    return;
end

% Check if key file exists
if ~exist(KEY_FILE, 'file')
    fprintf('❌ SSH key file not found: %s\n', KEY_FILE);
    fprintf('💡 Make sure you ran aws_setup_commands.sh first\n');
    return;
end

fprintf('✅ IP Address: %s\n', EC2_IP);
fprintf('✅ Key File: %s\n', KEY_FILE);
fprintf('\n🔧 Setting up cloud worker profile...\n');

try
    % Create the cloud worker profile
    c = parcluster('generic');
    c.Host = EC2_IP;
    c.NumWorkers = 16;
    c.OperatingSystem = 'unix';
    c.Username = 'ec2-user';
    c.IdentityFile = KEY_FILE;
    
    % Create job storage directory
    job_dir = 'C:\temp\matlab_jobs';
    if ~exist(job_dir, 'dir')
        mkdir(job_dir);
    end
    c.JobStorageLocation = job_dir;
    
    % Save the profile
    c.saveProfile('CloudWorker');
    
    fprintf('✅ Cloud worker profile created successfully!\n\n');
    
    % Test the connection
    fprintf('🔍 Testing connection to cloud worker...\n');
    fprintf('(This might take 30-60 seconds)\n');
    
    pool = parpool(c, 2);  % Start with just 2 workers for testing
    
    % Simple test
    fprintf('Running test computation...\n');
    test_result = 0;
    parfor i = 1:100
        test_result = test_result + i;
    end
    
    fprintf('✅ SUCCESS! Cloud worker is connected and working!\n');
    fprintf('🎉 Test result: %d (should be 5050)\n', test_result);
    
    delete(pool);  % Clean up
    
    fprintf('\n🎯 SETUP COMPLETE! Your cloud worker is ready to use.\n');
    fprintf('📚 Now you can run the example scripts below.\n\n');
    
catch ME
    fprintf('❌ Setup failed: %s\n', ME.message);
    fprintf('\n🔧 Troubleshooting:\n');
    fprintf('1. Make sure your EC2 instance is running\n');
    fprintf('2. Check your IP address is correct\n');
    fprintf('3. Verify the SSH key file exists\n');
    fprintf('4. Check your internet connection\n');
end

%% ========================================================================
%% STEP 2: EXAMPLE USAGE SCRIPTS (Copy any of these to use)
%% ========================================================================

fprintf('\n📝 COPY-PASTE EXAMPLES:\n');
fprintf('======================\n');
fprintf('Copy any of the examples below to use your cloud worker!\n\n');

%% Example 1: Simple Number Crunching
fprintf('%% EXAMPLE 1: Simple Number Crunching\n');
fprintf('%% Copy everything between the %%%% lines:\n\n');

example1_code = [
'%% Simple Cloud Computing Example', newline, ...
'fprintf(''Starting cloud workers...\n'');', newline, ...
'parpool(''CloudWorker'', 8);  % Start 8 workers', newline, newline, ...
'% Calculate squares of numbers (each worker does different numbers)', newline, ...
'numbers = 1:1000;', newline, ...
'squares = zeros(size(numbers));', newline, newline, ...
'fprintf(''Computing squares on cloud...\n'');', newline, ...
'tic;', newline, ...
'parfor i = 1:length(numbers)', newline, ...
'    squares(i) = numbers(i)^2;  % This runs on cloud workers!', newline, ...
'end', newline, ...
'computation_time = toc;', newline, newline, ...
'fprintf(''✅ Done! Computed %d squares in %.2f seconds\n'', length(numbers), computation_time);', newline, ...
'fprintf(''First 10 squares: %s\n'', mat2str(squares(1:10)));', newline, newline, ...
'% Clean up', newline, ...
'delete(gcp(''nocreate''));', newline, ...
'fprintf(''💰 Workers stopped to save money!\n'');'
];

fprintf('%s\n', example1_code);
fprintf('%%%%\n\n');

%% Example 2: Fake Cryptocurrency Analysis
fprintf('%% EXAMPLE 2: Fake Cryptocurrency Price Analysis\n');
fprintf('%% Copy everything between the %%%% lines:\n\n');

example2_code = [
'%% Cryptocurrency Analysis Example', newline, ...
'crypto_names = {''Bitcoin'', ''Ethereum'', ''Dogecoin'', ''Cardano'', ''Solana''};', newline, ...
'num_cryptos = length(crypto_names);', newline, ...
'days = 365;  % Analyze 1 year', newline, newline, ...
'fprintf(''Analyzing %d cryptocurrencies over %d days...\n'', num_cryptos, days);', newline, ...
'parpool(''CloudWorker'', 8);', newline, newline, ...
'% Simulate price analysis for each crypto', newline, ...
'price_volatility = zeros(num_cryptos, 1);', newline, newline, ...
'tic;', newline, ...
'parfor crypto = 1:num_cryptos', newline, ...
'    % Simulate complex price analysis (this runs on cloud!)', newline, ...
'    daily_prices = 1000 * (1 + cumsum(randn(days, 1) * 0.05));', newline, ...
'    price_volatility(crypto) = std(daily_prices);', newline, ...
'end', newline, ...
'analysis_time = toc;', newline, newline, ...
'% Display results', newline, ...
'fprintf(''✅ Analysis complete in %.2f seconds!\n'', analysis_time);', newline, ...
'for i = 1:num_cryptos', newline, ...
'    fprintf(''%s volatility: $%.2f\n'', crypto_names{i}, price_volatility(i));', newline, ...
'end', newline, newline, ...
'% Plot results', newline, ...
'figure;', newline, ...
'bar(price_volatility);', newline, ...
'set(gca, ''XTickLabel'', crypto_names);', newline, ...
'title(''Cryptocurrency Price Volatility Analysis'');', newline, ...
'ylabel(''Volatility ($)'');', newline, newline, ...
'delete(gcp(''nocreate''));'
];

fprintf('%s\n', example2_code);
fprintf('%%%%\n\n');

%% Example 3: Trading Strategy Simulation
fprintf('%% EXAMPLE 3: Trading Strategy Simulation\n');
fprintf('%% Copy everything between the %%%% lines:\n\n');

example3_code = [
'%% Trading Strategy Simulation', newline, ...
'num_strategies = 1000;  % Test 1000 different strategies', newline, ...
'trading_days = 252;    % 1 year of trading', newline, newline, ...
'fprintf(''Testing %d trading strategies...\n'', num_strategies);', newline, ...
'parpool(''CloudWorker'', 16);  % Use all 16 workers', newline, newline, ...
'strategy_profits = zeros(num_strategies, 1);', newline, newline, ...
'tic;', newline, ...
'parfor strategy = 1:num_strategies', newline, ...
'    % Simulate one trading strategy', newline, ...
'    initial_money = 10000;  % Start with $10,000', newline, ...
'    current_money = initial_money;', newline, ...
'    ', newline, ...
'    for day = 1:trading_days', newline, ...
'        % Random trading decision (buy/sell/hold)', newline, ...
'        market_move = randn() * 0.02;  % Market moves ±2% per day', newline, ...
'        trading_decision = randn();    % Random strategy', newline, ...
'        ', newline, ...
'        if trading_decision > 0.5', newline, ...
'            current_money = current_money * (1 + market_move);', newline, ...
'        end', newline, ...
'    end', newline, ...
'    ', newline, ...
'    strategy_profits(strategy) = current_money - initial_money;', newline, ...
'end', newline, ...
'simulation_time = toc;', newline, newline, ...
'% Analyze results', newline, ...
'profitable_strategies = sum(strategy_profits > 0);', newline, ...
'best_profit = max(strategy_profits);', newline, ...
'worst_loss = min(strategy_profits);', newline, ...
'average_profit = mean(strategy_profits);', newline, newline, ...
'fprintf(''✅ Simulation complete in %.2f seconds!\n'', simulation_time);', newline, ...
'fprintf(''📊 Results:\n'');', newline, ...
'fprintf(''   Profitable strategies: %d out of %d (%.1f%%)\n'', profitable_strategies, num_strategies, profitable_strategies/num_strategies*100);', newline, ...
'fprintf(''   Best profit: $%.2f\n'', best_profit);', newline, ...
'fprintf(''   Worst loss: $%.2f\n'', worst_loss);', newline, ...
'fprintf(''   Average profit: $%.2f\n'', average_profit);', newline, newline, ...
'% Plot histogram of profits', newline, ...
'figure;', newline, ...
'histogram(strategy_profits, 50);', newline, ...
'title(''Trading Strategy Profit Distribution'');', newline, ...
'xlabel(''Profit/Loss ($)'');', newline, ...
'ylabel(''Number of Strategies'');', newline, newline, ...
'delete(gcp(''nocreate''));'
];

fprintf('%s\n', example3_code);
fprintf('%%%%\n\n');

%% Final Instructions
fprintf('🎯 HOW TO USE THESE EXAMPLES:\n');
fprintf('=============================\n');
fprintf('1. First run this setup script (the part above)\n');
fprintf('2. Copy any example code between the %%%% lines\n');
fprintf('3. Paste it into a new MATLAB script or command window\n');
fprintf('4. Press F5 or click "Run" - that''s it!\n\n');

fprintf('💡 REMEMBER:\n');
fprintf('- Always start with: parpool(''CloudWorker'', X)\n');
fprintf('- Use "parfor" instead of "for" for parallel loops\n');
fprintf('- Always end with: delete(gcp(''nocreate''))\n\n');

fprintf('🎉 You''re ready to use cloud computing with MATLAB!\n');
